ANAHTAR TERIMLER

___numpy.ndarray___ - n-dimensional Numpy array, the core object that underpins Pandas DataFrames - Pandas DataFrame'lerinin temelini oluşturan n boyutlu Numpy dizisi.

___pyspark.sql.DataFrame___ - Distributed dataframe object in PySpark for working with large  - Buyuk veri kümeleriyle çalışmak için PySpark'ta kullanılan dağıtılmış veri çerçevesi nesnesi.

___dask.dataframe.DataFrame___ - Dask dataframe that partitions Pandas dataframe across multiple cores - Pandas veri çerçevesini birden fazla çekirdek üzerinde bölümlere ayıran Dask veri çerçevesi.

___np.random.randn()___ - Generate an ndarray with random values from a normal distribution - Normal dağılımdan rastgele değerler içeren bir ndarray oluşturur.

___df.persist()___ - Trigger caching of a PySpark dataframe into memory or disk storage - PySpark veri çerçevesinin belleğe veya disk depolama alanına önbelleğe alınmasını tetikler.

In [27]:
import pandas as pd
import numpy as np

# numpy.ndarray
data = np.random.randn(5, 4)  # Generate 5x4 ndarray 
df = pd.DataFrame(data) # Underlying structure of Pandas DataFrame
print(df)

# np.random.randn()  
df = pd.DataFrame(np.random.randn(5, 4), 
                  columns=['A', 'B', 'C', 'D']) 
print(df)

          0         1         2         3
0 -0.954371  0.209828 -1.990402 -0.844585
1 -1.067350 -2.522664 -0.991478  2.490378
2  1.134482 -1.328848  0.363169  1.179248
3  0.739465 -0.380486  1.728283 -0.237407
4 -1.818626  0.289751 -0.630910  0.392949
          A         B         C         D
0  0.835194  1.544882  0.379511 -3.070871
1 -0.863050  0.640149 -0.551304  0.287622
2  0.163692  1.032595  0.766458 -1.087124
3 -0.340240 -0.378342 -0.813700 -0.533282
4 -1.213548  0.867942 -0.166456 -0.941334

___Creating Numpy Arrays in Python___

ndarray

1. Size set at creation (Boyut oluşturulurken belirlenir)
Bir ndarray oluşturduğunda bellekte sabit bir yer ayrılır. Python listelerinin aksine, NumPy dizileri dinamik olarak büyüyecek şekilde tasarlanmamıştır. Boyutu değiştirmek istersen teknik olarak yeni bir dizi oluşturulur ve eskisi silinir.

2. Single data type (Tek veri tipi - Homojenlik)
Bu en kritik özelliklerden biridir. Bir ndarray içindeki tüm elemanlar aynı tipte (örneğin hepsi int64 veya float64) olmalıdır. Bu homojenlik, Python'ın her eleman için ayrı ayrı tip kontrolü yapmasını engeller ve işlemlerin vektörize edilerek çok hızlı çalışmasını sağlar.

3. Not limited to İki Boyut (Sınırsız Boyut)
Pandas DataFrame'ler genellikle 2 boyutludur (satır ve sütun). Ancak ndarray şunları yapabilir:

        1D: Bir vektör (Örn: [1, 2, 3])

        2D: Bir matris (Örn: Resimlerin siyah-beyaz piksel değerleri)

        3D ve üzeri: Tensörler (Örn: Renkli resimler - RGB kanalları veya zaman serisi verileri)

4. Can be reshaped (Yeniden Şekillendirilebilir)
Dizinin içindeki verileri ve toplam eleman sayısını değiştirmeden, görünümünü (boyutlarını) değiştirebilirsin. Örneğin, 12 elemanlı tek bir satırı, 3x4'lük bir matrise dönüştürebilirsin.

In [28]:
import numpy as np

Creating arrays

In [29]:
data=[1, 2, 3]
first_arr= np.array(data) # Convert list to ndarray
print(first_arr)

[1 2 3]

In [30]:
data=[[1, 2, 3], 
      [4, 5, 6], 
      [7, 8, 9]]
second_arr= np.array(data) # Convert list of lists to 2D ndarray
print(second_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Dimensions and Shapes

In [31]:
OneDim=np.arange(1, 21) # Create 1D array with values from 1 to 21
OneDim

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
pd.DataFrame(OneDim) # Convert 1D array to DataFrame

     0
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  11
11  12
12  13
13  14
14  15
15  16
16  17
17  18
18  19
19  20

In [33]:
list_of_lists = [[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]]

TwoDim= np.array(list_of_lists) # Convert list of lists to 2D
TwoDim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
pd.DataFrame(TwoDim) # Convert 2D array to DataFrame

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

-------------------

In [35]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(3, 12, 4)

array([ 3,  7, 11])

______________________

In [39]:
OneDim.shape

(20,)

In [40]:
OneDim.ndim

1

In [41]:
OneDim.size

20

In [42]:
print(TwoDim.shape)
print(TwoDim.ndim)
print(TwoDim.size)

(3, 3)
2
9

Tek Dimension'dan Cift Dimension'a cevirmek

In [43]:
oned= np.arange(1, 21) # Create 1D array with values from 1 to 21
twod=oned.reshape(4, 5) # Reshape 1D array to 2D array with 4 rows and 5 columns
twod

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [44]:
twod.reshape(2, 3) # Reshape 2D array to 2 rows and 3 columns   
# This will raise an error because the total number of elements (20) 
# cannot be reshaped into a 2x3 array (which requires 6 elements).

ValueError: cannot reshape array of size 20 into shape (2,3)

In [ ]:
twod=twod.reshape(2,2,5) # Reshape 2D array to 3D array with 2 blocks, 2 rows, and 5 columns
twod

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

Setting Data Types

In [ ]:
darray= np.arange(0,100)
darray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [45]:
darray.dtype

dtype('int64')

In [46]:
darray.nbytes

800

In [49]:
darray[12]="a"   
# This will raise an error because the array is of integer type and cannot hold a string value.

ValueError: invalid literal for int() with base 10: 'a'

In [53]:
darray[0]=0.4
darray  
#Bu degisiklikte farliligi gormek icin yazildi. Ancak bu da hata verecektir cunku darray integer tipinde ve ondalikli sayi atanamaz.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Broadcasting - Matriksler uzerinde Islemler

In [61]:
A1=np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

In [62]:
A1.shape

(3, 3)

In [64]:
A2=np.array([[1,1,1],
             [1,1,1],
             [1,1,1]])

In [65]:
A1+A2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [66]:
A1+4

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [68]:
A3=np.array([1, 1,1])

In [71]:
A4=np.arange(0, 10).reshape(2,1,5)
A4

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [72]:
A5= np.arange(14).reshape(2,7, 1)
A5

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13]]])

In [73]:
A6=A4+A5
A6

array([[[ 0,  1,  2,  3,  4],
        [ 1,  2,  3,  4,  5],
        [ 2,  3,  4,  5,  6],
        [ 3,  4,  5,  6,  7],
        [ 4,  5,  6,  7,  8],
        [ 5,  6,  7,  8,  9],
        [ 6,  7,  8,  9, 10]],

       [[12, 13, 14, 15, 16],
        [13, 14, 15, 16, 17],
        [14, 15, 16, 17, 18],
        [15, 16, 17, 18, 19],
        [16, 17, 18, 19, 20],
        [17, 18, 19, 20, 21],
        [18, 19, 20, 21, 22]]])

In [74]:
A6.shape

(2, 7, 5)

Matrix Operations

In [75]:
M1= np.arange(9).reshape(3,3)
M1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
M1.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [80]:
M1.diagonal()   #matriksteki diyagonal sayilari verir

array([0, 4, 8])

In [77]:
M2= np.arange(2, 11).reshape(3,3)
M2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [81]:
M1 @ M2  #Matris carpimi yapar

array([[ 21,  24,  27],
       [ 66,  78,  90],
       [111, 132, 153]])